/**
 * Downloads the webfonts this site uses and writes a self-hosted @font-face
 * stylesheet, so the page makes no request to fonts.googleapis.com or
 * fonts.gstatic.com at runtime.
 *
 * Security rationale: every third-party origin the browser is allowed to fetch
 * from is both a supply-chain vector (a compromised CDN can serve anything the
 * CSP permits from that origin) and a privacy leak (the CDN sees each visitor's
 * IP and Referer). Removing them lets the CSP drop to `font-src 'self'` and
 * `style-src` without an external allowance.
 *
 * Run: node scripts/fetch-fonts.mjs   (only needed when the font list changes)
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const OUT_DIR = new URL('../public/fonts/', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')
const CSS_OUT = new URL('../src/fonts.css', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')

const FAMILIES = [
  'Inter:wght@400;500;600',
  'JetBrains+Mono:wght@400;500',
  'Space+Grotesk:wght@500;600;700',
]

// A modern browser UA is required or Google serves legacy formats instead of woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36'

const url = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f}`).join('&')}&display=swap`

const res = await fetch(url, { headers: { 'User-Agent': UA } })
if (!res.ok) throw new Error(`Google Fonts CSS returned ${res.status}`)
let css = await res.text()

await mkdir(OUT_DIR, { recursive: true })

// Keep only latin and latin-ext; the other subsets are dead weight for this site.
const blocks = css.split('/*').filter(Boolean)
const kept = blocks.filter((b) => /^\s*(latin|latin-ext)\s*\*\//.test(b))

let out = `/*
 * Self-hosted webfonts. Generated by scripts/fetch-fonts.mjs — do not edit by hand.
 * Self-hosted so the page contacts no third-party origin at runtime.
 */\n\n`

const downloads = new Map()
for (const block of kept) {
  let body = '/*' + block
  const urls = [...body.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/g)]
  for (const [, remote] of urls) {
    const name = remote.split('/').slice(-2).join('-')
    downloads.set(name, remote)
    body = body.replace(remote, `/fonts/${name}`)
  }
  out += body.trim() + '\n\n'
}

let bytes = 0
for (const [name, remote] of downloads) {
  const r = await fetch(remote, { headers: { 'User-Agent': UA } })
  if (!r.ok) throw new Error(`${name} -> ${r.status}`)
  const buf = Buffer.from(await r.arrayBuffer())
  bytes += buf.length
  await writeFile(join(OUT_DIR, name), buf)
}

await writeFile(CSS_OUT, out, 'utf8')
console.log(`Downloaded ${downloads.size} woff2 files (${(bytes / 1024).toFixed(1)} KB) to public/fonts/`)
console.log(`Wrote ${CSS_OUT}`)
