/**
 * Generates dist/_headers, including a Content-Security-Policy whose script-src
 * carries the SHA-256 hash of every inline <script> in the built HTML.
 *
 * The hash is computed rather than hardcoded on purpose. A CSP hash that drifts
 * out of sync with the script it authorises fails *silently and late* — the page
 * still serves, the script is simply blocked, and here that means the theme
 * flashes and no one notices until a user reports it. Deriving it from the built
 * artefact means it cannot drift.
 *
 * Runs as part of `npm run build`, after prerendering.
 */
import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { readdir } from 'node:fs/promises'
import { join } from 'node:path'

const DIST = new URL('../dist/', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')

/** SHA-256 hashes of inline executable scripts across every built HTML file. */
async function inlineScriptHashes() {
  const hashes = new Set()
  const files = (await readdir(DIST)).filter((f) => f.endsWith('.html'))

  for (const file of files) {
    const html = await readFile(join(DIST, file), 'utf8')
    // Only <script> without src. `type="application/ld+json"` is data, not code,
    // and browsers do not apply script-src to it — but hashing it is harmless and
    // guards against a browser that does.
    for (const m of html.matchAll(/<script\b(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)) {
      const body = m[1]
      if (!body.trim()) continue
      hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`)
    }
  }
  return [...hashes]
}

const scriptHashes = await inlineScriptHashes()

const csp = [
  "default-src 'self'",
  `script-src 'self' ${scriptHashes.join(' ')}`,
  // 'unsafe-inline' is required for style, not laziness: the prerendered markup
  // contains literal style="" attributes and React writes inline styles at
  // runtime. It is an accepted trade here because the site renders zero
  // user-supplied or remote content, so there is no injection path to abuse it.
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "manifest-src 'self'",
  'upgrade-insecure-requests',
].join('; ')

const headers = `# Generated by scripts/gen-headers.mjs — do not edit by hand.
# Netlify applies these on top of netlify.toml.

/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  Permissions-Policy: accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), display-capture=(), document-domain=(), encrypted-media=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), serial=(), usb=(), xr-spatial-tracking=(), interest-cohort=()
  X-DNS-Prefetch-Control: off

/assets/*
  Cache-Control: public, max-age=31536000, immutable

/fonts/*
  Cache-Control: public, max-age=31536000, immutable
  Cross-Origin-Resource-Policy: same-origin

/robots.txt
  Content-Type: text/plain; charset=utf-8
  Cache-Control: public, max-age=3600

/sitemap.xml
  Content-Type: application/xml; charset=utf-8
  Cache-Control: public, max-age=3600
`

await writeFile(join(DIST, '_headers'), headers, 'utf8')

/*
 * Vercel ignores `_headers` — that is Netlify's format. Without an equivalent,
 * a Vercel copy of this site would serve with NO security headers at all while
 * looking identical. Both are generated here from the same values so the two
 * deployments cannot drift apart.
 *
 * This is written to the PROJECT ROOT, not dist/. Vercel reads vercel.json from
 * the repository root *before* it runs the build, so a copy inside dist/ would
 * never be seen by a git-integration deployment. The consequence is that the file
 * is committed, and its CSP hashes must be kept current — `npm run verify:headers`
 * fails if the committed copy has drifted from what the build produces.
 */
const securityHeaders = [
  { key: 'Content-Security-Policy', value: csp },
  { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' },
  { key: 'X-Frame-Options', value: 'DENY' },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  { key: 'Cross-Origin-Opener-Policy', value: 'same-origin' },
  { key: 'Cross-Origin-Resource-Policy', value: 'same-origin' },
  { key: 'X-DNS-Prefetch-Control', value: 'off' },
  {
    key: 'Permissions-Policy',
    value:
      'accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), display-capture=(), document-domain=(), encrypted-media=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), serial=(), usb=(), xr-spatial-tracking=(), interest-cohort=()',
  },
]

const vercelConfig = {
  $schema: 'https://openapi.vercel.sh/vercel.json',
  buildCommand: 'npm run build',
  outputDirectory: 'dist',
  framework: null,
  cleanUrls: false,
  trailingSlash: false,
  headers: [
    { source: '/(.*)', headers: securityHeaders },
    {
      source: '/assets/(.*)',
      headers: [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }],
    },
    {
      source: '/fonts/(.*)',
      headers: [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }],
    },
  ],
}

const ROOT = new URL('../', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')
const rootVercel = join(ROOT, 'vercel.json')
const nextVercel = JSON.stringify(vercelConfig, null, 2) + '\n'

// --check exits non-zero if the committed vercel.json has drifted from what this
// build produces, rather than silently deploying stale CSP hashes.
if (process.argv.includes('--check')) {
  let current = null
  try {
    current = await readFile(rootVercel, 'utf8')
  } catch {
    /* missing counts as drifted */
  }
  if (current !== nextVercel) {
    console.error('vercel.json is out of date. Run `npm run build` and commit the result.')
    process.exit(1)
  }
  console.log('vercel.json is in sync with the current build.')
} else {
  await writeFile(rootVercel, nextVercel, 'utf8')
  console.log(
    `Wrote dist/_headers and vercel.json with ${scriptHashes.length} inline-script hash(es)`,
  )
  scriptHashes.forEach((h) => console.log(`  ${h}`))
}
